#!/usr/bin/env python
import os
import bmemcached

try:
	# read memcached connection parameters from environment
	memcached_endpoint = '%s:%s' % (os.environ['OPENSHIFT_MEMCACHED_HOST'], os.environ['OPENSHIFT_MEMCACHED_PORT'])
	memcached_username = os.environ['OPENSHIFT_MEMCACHED_USERNAME']
	memcached_password = os.environ['OPENSHIFT_MEMCACHED_PASSWORD']

	# connect to memcached
	client = bmemcached.Client((memcached_endpoint,), memcached_username, memcached_password)
except KeyError:
	client = None

def application(environ, start_response):
	status = '200 OK'
	components = environ['PATH_INFO'].strip('/').split('/')

	if len(components) == 0:
		# haproxy pings us with HEAD /
		response_body = ''
	elif len(components) == 1 and components[0] == '/health':
		response_body = 'UP'
	elif len(components) == 2:
		action, name = components
		assert action == 'get'

		# read key value
		response_body = client.get(name)
	elif len(components) == 3:
		action, name, value = components
		assert action == 'set'

		# save key value
		client.set(name)
		response_body = 'OK'
	else:
		status, response_body = '404 Not Found', 'Valid URLs:\n  /set/{name}/{value}\n  /get/{name}\n'

	response_headers = [('Content-Type', 'text/plain'), ('Content-Length', str(len(response_body)))]
	start_response(status, response_headers)
	return [response_body]

#
# Below for testing only
#
if __name__ == '__main__':
	from wsgiref.simple_server import make_server
	httpd = make_server('localhost', 8051, application)
	# Wait for a single request, serve it and quit.
	httpd.handle_request()
